Repository pupitoe/cube_3d, pull requests merged in 2024-04, with the labels that each got.

#32 Wall color
  Makefile
  headers/ft_data_wall.h
  headers/ft_dda.h
  sources/ft_game/ft_dda.c
  sources/ft_game/ft_map_wall.c
Labels: enhancement

#33 Fix: segfault :(
  headers/ft_color.h
  headers/ft_data.h
  sources/ft_game/ft_map_wall.c
  sources/ft_game/ft_move.c
Labels: bug

#35 check for duplicate player
  headers/ft_parser.h
  sources/ft_parser/flood.c
  sources/ft_parser/ft_parser.c
  sources/ft_parser/load.c
  sources/ft_parser/utils.c
  sources/ft_parser/validate.c
Labels: bug

#37 patched overflow and segfault OUPS
  headers/ft_parser.h
  map/debug.cub
  sources/ft_parser/celling.c
  sources/ft_parser/floor.c
  sources/ft_parser/ft_parser.c
  sources/ft_parser/utils.c
  sources/ft_parser/validate.c
Labels: bug

#38 %.o are now compiled in the objects subdirectory
  Makefile
Labels: enhancement

#39 added error message for wrong file extension
  sources/ft_parser/ft_parser.c
Labels: enhancement

#43 Player size
  headers/ft_data.h
  headers/ft_game.h
  headers/ft_move.h
  sources/ft_game/ft_collision.c
  sources/ft_game/ft_game.c
  sources/ft_game/ft_images.c
  sources/ft_game/ft_move.c
  sources/ft_game/ft_move_hook.c
  sources/ft_game/ft_ray.c
  sources/ft_parser/ft_parser.c
Labels: enhancement

#46 Fix: norm
  sources/ft_game/ft_map.c
  sources/ft_game/ft_ray.c
Labels: norm

#47 Fix: change name of function hook
  sources/ft_game/ft_game.c
Labels: norm

#61 Fix: error in stdin to stdout
  sources/ft_parser/error.c
Labels: bug

#60 Refactor texture
  Makefile
  asset/door.png
  headers/ft_data.h
  headers/ft_dda.h
  headers/ft_game.h
  headers/ft_move.h
  map/door.cub
  map/test.cub
  sources/ft_game/ft_collision.c
  sources/ft_game/ft_dda.c
  sources/ft_game/ft_dda_call.c
  sources/ft_game/ft_game.c
  sources/ft_game/ft_interact.c
  sources/ft_game/ft_map_wall.c
  sources/ft_game/ft_textures.c
  sources/ft_game/ft_wall_texture.c
  sources/ft_parser/converter.c
  sources/ft_parser/map.c
  sources/ft_parser/utils.c
Labels: enhancement

#63 Feat: change methode to get rotat
  Makefile
  headers/ft_data.h
  headers/ft_game.h
  sources/ft_game/ft_game.c
  sources/ft_game/ft_mouse.c
Labels: enhancement

#64 opened door switch to green
  sources/ft_game/ft_map.c
Labels: enhancement

#65 patched print
  sources/ft_game/ft_map.c
Labels: bug

#68 Fix: tipo
  headers/ft_print.h
  sources/ft_game/ft_print_hud.c
Labels: bug

#69 Fix: norm
  sources/ft_game/ft_print_hud.c
Labels: norm

#71 Fix: delete ft_ray
  Makefile
  headers/ft_print.h
  sources/ft_game/ft_ray.c
Labels: enhancement

#70 Fix: komamie
  headers/ft_game.h
  sources/ft_game/ft_game_hook.c
  sources/ft_game/ft_konami.c
Labels: bug

#73 floor data verification added
  sources/ft_parser/validate.c
Labels: bug

#77 Feat test
  map/circul.cub
  map/debug.cub
  map/invalide.cub
  map/invalide_color.cub
  map/invalide_map.cub
  map/invalide_map2.cub
  map/invalide_map3.cub
  map/invalide_param.cub
  map/invalide_param2.cub
  map/invalide_param3.cub
  map/invalide_texture.cub
  map/maptest1.cub
  map/maptest2.cub
Labels: enhancement
